In [ ]:
from pathlib import Path
import pandas as pd



DATA_PATH = Path("data/ActivityCodes.csv")
if not DATA_PATH.exists():
    raise FileNotFoundError(f"Could not find data file at: {DATA_PATH.resolve()}")

df = pd.read_csv(DATA_PATH)

print(f"Loaded {len(df)} rows and {len(df.columns)} columns from {DATA_PATH}")
df.head()

Loaded 257 rows and 4 columns from data/ActivityCodes.csv

,Activity Code,Funding Category,Title,Description
0,C06,Construction and Modernization,Research Facilities Construction Grant,"To provide matching Federal funds, up to 75%, ..."
1,D43,Research Training and Career Development,International Research Training Grants,To support research training programs for US a...
2,D71,Research Training and Career Development,International Research Training Planning Grant,To plan for the preparation of an application ...
3,DP1,Research and Development,NIH Director’s Pioneer Award (NDPA),To support individuals who have the potential ...
4,DP2,Research and Development,NIH Director’s New Innovator Awards,To support highly innovative research projects...

In [21]:
keep_cols = [
    "Activity Code",
    "Title" ]

df = df[keep_cols]

df.head()

  Activity Code                                           Title
0           C06          Research Facilities Construction Grant
1           D43          International Research Training Grants
2           D71  International Research Training Planning Grant
3           DP1             NIH Director’s Pioneer Award (NDPA)
4           DP2             NIH Director’s New Innovator Awards

In [ ]:
output_path = Path("../data")
df.to_csv(output_path, index=False) 

print(f"Saved CSV: {output_path.resolve()}")
print(f"Rows: {len(df):,}")

Saved CSV: /Users/niko/Documents/GitHub/KBR-Internship/backend/data
Rows: 257